### PR TITLE
Number.js to execute validation 

### PR DESCRIPTION
**Pull request by maplechori**
Number.js to execute validation 
- Changed this to allow the deletion of all numbers to pop the validation error
- setValue is no longer valid

### CODE REVIEW

**Comment by stevehu** [comment]
@maplechori Thanks for your pull request. I am reviewing the changes and wondering if you could elaborate the reason to make the change. The old logic is to prevent other non-number value assigned to this field. If it is number, it does the validation. Otherwise, it uses the last valid number which doesn't need to be validated. Have you found some strange behaviour? 
Best regards.

**Comment by maplechori** [comment]
I have found you can delete all numbers and there is not a "missing required field" message. It also shows the form as valid despite having an empty required field. I realized this issue was more extensive and this change is not enough.

**Comment by stevehu** [comment]
I might be different versions we are using. I tried the demo linked below and you cannot clear the number field once it is entered. Let me know if you see different behaviour which might be broken in the latest version. 

http://networknt.github.io/react-schema-form/

try the Basic JSON schema type example.

**Comment by maplechori** [comment]
I see, the one I am using I got from npm. I gather that not letting users
delete all numbers is the desired behavior?

**Comment by stevehu** [comment]
It is very hard to standardize the behaviour as different people will ask for different things. I think it should allow user to remove numbers but give error if the field is required. I think this has been changed several times and I have lost track already:) I can spend sometime to dig into it once I am free. I would be great if you could help to get it fixed. Thanks.

**Comment by maplechori** [comment]
I will try to look into it, been swamped at work.

**Comment by maplechori** [comment]
Ok I just installed and ran the master branch. 

I get the same error that this pull fixes. 

ExamplePage.onModelChange: ["name"] 1
Number.js:37 Uncaught TypeError: this.refs.numberField.setValue is not a function
    at Number.preValidationCheck (http://localhost:8080/form.entry.js:95023:40)
    at TextField._this.handleInputChange (http://localhost:8080/form.entry.js:95435:22)
    at Object.executeOnChange (http://localhost:8080/form.entry.js:14111:35)
    at ReactDOMComponent._handleChange (http://localhost:8080/form.entry.js:13928:39)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8080/form.entry.js:6561:17)
    at executeDispatch (http://localhost:8080/form.entry.js:6342:22)
    at Object.executeDispatchesInOrder (http://localhost:8080/form.entry.js:6365:6)
    at executeDispatchesAndRelease (http://localhost:8080/form.entry.js:5751:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8080/form.entry.js:5762:11)
    at Array.forEach (native)

**Comment by maplechori** [comment]
Ok fixed validation, feel free to merge. 

Changed it so that users can delete all numbers/type a minus sign and it will mark it as missing property and won't validate it.

Cheers

**Comment by stevehu** [comment]
Thanks @maplechori for your contribution.

**Pull request merged**
