### PR TITLE
Update to material-ui v4

### PR DESCRIPTION
**Pull request by psamim**

### CODE REVIEW

**Comment by stevehu** [comment]
@psamim Thanks a lot for your help. I tried to run `npm run test` and found several test cases failed. I am wondering if this is due to the peer dependency of React. Do you think we should upgrade to the latest React?

**Comment by psamim** [comment]
Yes I see the errors, I am not sure. I updated react but still see many errors. @naeemba Do you have any idea?

**Comment by naeemba** [comment]
Sorry for the delay, I tested the app, and seems the tests are working fine with the new changes, the problem was about material-ui using react hooks which introduced in react v16.8.x but the project's react version was 16.7 and also another problem with enzyme which when I updated it, the problem has been solved.

**Comment by stevehu** [comment]
@psamim @naeemba Thanks a lot for your help. I am testing now but got some gateway issue with npm install. Will continue working on it after several meetings.

**Comment by stevehu** [comment]
@naeemba I am testing from your repository with `npm test` and got the following console error. I don't know if this is only for my environment. 

```
 console.error node_modules/react-dom/cjs/react-dom-server.node.development.js:105
    Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
        in ForwardRef(ButtonBase)
        in WithStyles(ForwardRef(ButtonBase))
        in ForwardRef(IconButton)
        in WithStyles(ForwardRef(IconButton))
        in div
        in ForwardRef(Paper)
        in WithStyles(ForwardRef(Paper))
        in ForwardRef(Card)
        in WithStyles(ForwardRef(Card))
        in div
        in div
        in ArrayComponent
        in WithStyles(ArrayComponent)
        in Composed
        in div
        in SchemaForm

```

**Comment by naeemba** [comment]
@stevehu sorry I was a little busy, I fixed the warnings you mentioned and also I've upgraded different other dependencies, and have added a few flow declaration files. Please check if there are any problems with the new changes.
Thanks,
Naeem,

**Comment by stevehu** [comment]
[Update to material-ui v4](https://trello.com/c/0fbRRy9G/301-update-to-material-ui-v4)

**Comment by stevehu** [comment]
@naeemba Thanks a lot for your help. My React is a little bit rusty to understand all the changes but it works perfectly. No worry about the time. We are working on an open source project and there is no obligation. I will release a new version after some testing.

**Pull request merged**
