### PR TITLE
fixes demo

### PR DESCRIPTION
**Pull request by JFrankfurt**
The example wasn't functioning after the material/react upgrade, this fixes it.
The form textarea had a z-index of -1 that was keeping us from adding any input.

I also removed unused or unneeded libraries in the example.
- less-loader: we don't have any less in the example
- react-select: we already have a select component in MateralUI
- jquery: was only being used for ajax, and `window.fetch` does the same thing.
- I made explicit the yarn/npm usage between the main and example repos (see `engines`)

### CODE REVIEW

**Comment by stevehu** [comment]
@JFrankfurt A lot of changes makes perfect sense. Why did you close it?

**Comment by JFrankfurt** [comment]
@stevehu I'd forgotten to go through the build process on the main repo with the modified `package.json`. I'll resubmit it here in a second. I should include the new `lib` and `dist` directories, right?

**Comment by stevehu** [comment]
lib is needed but I guess the dist is not necessary unless for publishing.

**Comment by JFrankfurt** [comment]
See #116 for current PR. Happy to pull the `dist` out if you'd like.

**Pull request closed without merging**
