### PR TITLE
passes click events to materialUI and does some housekeeping

### PR DESCRIPTION
**Pull request by JFrankfurt**
Updates to `material-ui` v.0.20.2, which removes the need for the `react-tap-event-plugin` dependency and `onTouchTap` handlers. (safe `onClick` for everyone! 🎉)

housekeeping list:
- removed unused dependencies and log statements in all the files I touched
- standardized single/double quotes in the files I touched (looked like single was being used more)
- removed jquery dependency in the example and just used native fetch
- corrected improper of `JSON.stringify`
- added source-maps to the example build
- removed unused style loaders

I am planning on submitting the same PR for RCSelect if no one objects.

### CODE REVIEW

**Comment by JFrankfurt** [comment]
I just noticed #111. That should make most of this obsolete.

**Comment by stevehu** [comment]
@JFrankfurt I just merged #111 into the develop branch and planning to merge back to master for the next release. Do you want to have your PR to merge to master and create a release? Thanks.

**Comment by JFrankfurt** [comment]
@stevehu sounds good to me!

(Though I am *very* much looking forward to having @dogada's work released.)

**Comment by stevehu** [comment]
@JFrankfurt I am testing it now and it will be released soon. Thanks.

**Pull request closed without merging**
