### PR TITLE
Array tuple example/support

### PR DESCRIPTION
**Pull request by fauxsoup**
This is an incomplete pull request. I'm seeking assistance in making it happen.

JSON Schema distinguishes between two types of array validation: `List` and `Tuple`. Essentially, the `items` attribute of an `array` may be either: 1) a single JSON schema, indicating the array is a list of objects matching said schema; or 2) an array of JSON schemas, indicating the array is a tuple where each item may be its own type. Please see here for reference: https://json-schema.org/understanding-json-schema/reference/array.html

Currently react-schema-form appears to only support the `List` usage. I would like to extend it to support the `Tuple` usage as well.

I'm currently trying to work through this on my own, but am struggling to find an obvious path. I would appreciate any input or advice. In particular, I'm not sure how to adjust the form and schema processing to support this approach.

Would it make sense to create a separate `Tuple` component to handle this completely separately from the `List` case? If so, should I also create a `tuple` form creator in `src/utils`? I think that would be the best approach, but I'm really not certain!

### CODE REVIEW

**Comment by stevehu** [comment]
This is very interesting. For an array, it is easy to implement with the add button to add the same component multiple times. For a tuple, as each item has its schema and they might be different. It is more like a fieldset, isn't it? Do you think we can use fieldset to implement it? Or something that is similar that we call it Tuple?

**Comment by fauxsoup** [comment]
I think that would be the right approach. I tried this by providing a custom `mapper` component that runs `builder` on `form.items` (e.g., just like fieldset), but inside the tuple no form controls were rendered in the example. When I added debug output, it showed that the `form` object had no `schema` property in the tuple's children. I thought this might have to do with `lookup` in `utils`, but I'm not sure.

**Comment by stevehu** [comment]
I think you need to update the utils to make sure the component is constructed correctly. When I work on it, I added a lot of debugging info. The logic is pretty complicated and the only way is to debug into it.

**Comment by fauxsoup** [comment]
In theory this works. Much less painful than I thought it would be. Using FieldSet for rendering makes sense.

**Comment by fauxsoup** [comment]
It renders correctly, but the produced model fails in my more complex test case. Still working on it.

**Comment by fauxsoup** [comment]
This fixes the produced model. Minor bug in selectOrSet that would ignore arrays in the first two elements.

**Comment by stevehu** [comment]
@fauxsoup Let me know when you complete the work and I can review, merge and publish. I look at what we have so far and it looks good. Thanks a lot for the addition.

**Comment by fauxsoup** [comment]
@stevehu I believe it's done now. I've found no bugs while working with a variety of different schemas and forms, although there are probably edge cases I haven't hit. Everything appears to work as before, but with added support for the tuple array syntax.

**Comment by stevehu** [comment]
@fauxsoup Could you please add more examples? This is a very important new feature and for now, the only way for other users to learn how to use it is the examples. Thanks.

**Comment by fauxsoup** [comment]
I've added more examples and fixed a bug I found in the `Array` component. Let me know you need more!

**Pull request merged**
