### PR TITLE
fix number can not empty

### PR DESCRIPTION
**Pull request by weilaihui**
I add form type

### CODE REVIEW

**Comment by stevehu** [comment]
@weilaihui Thanks a lot for your help.

**Comment by weilaihui** [comment]
@stevehu If it's convenient for you, can you give me a little eth, I want to "Submit Work" in gitcoin.My eth address is:0x061502AA01b18194b74B14879A7e3514fDC69A50

**Comment by stevehu** [comment]
@weilaihui I am the owner of this open source project but I don't have eth account. The funding is provided by one of the contributors and it looks like you need to go https://gitcoin.co/issue/networknt/react-schema-form/76 to claim it. I think this is a very good idea and I might setup a eth account in the future to collect donations in order to fund defect fixing. I looked at the link above the status is still started work and I think you need to submit work somehow in order to claim. Thanks.

**Comment by weilaihui** [comment]
@stevehu submit work need some eth gas.

**Pull request merged**
