### PR TITLE
Allow htmlClass on fieldset elements

### PR DESCRIPTION
**Pull request by fauxsoup**
If I understand the form definition correctly, this should be supported. I was looking to use a feature like this recently, but had to settle for adding `style` properties instead.

### CODE REVIEW

**Comment by stevehu** [comment]
@fauxsoup I am amazed by the creativities of our users. Yes, this makes perfect sense and I never thought about it. Would you be able to add a small example to show other users how to style the fieldset? Thanks.

**Comment by fauxsoup** [comment]
Will this be sufficient? Wasn't sure where to put it, so I figured a new test was appropriate.

**Comment by stevehu** [comment]
This is really good. I've learned a lot of users are looking at the examples instead of the test cases.

**Comment by stevehu** [comment]
@fauxsoup The release 0.6.13 is out with this PR. Thanks a lot for your help. 

https://github.com/networknt/react-schema-form/releases/tag/0.6.13

**Pull request merged**
